### ISSUE TITLE
Dockerize SCION Processes

### ISSUE THREAD

**Issue by worxli** [scionproto/scion-distroless#2]
Run SCION in a docker compose setup, with a docker image per service:

- Configuration, data/cache/log dirs, domain sockets would all be bind-mounted inside the container.
- Most containers would run in a non-privileged fashion: dispatcher, sciond, bs, ps, cs.
- The BR & SIG would run with --privilege --net=host (or similar), to allow them direct access/control for networking.
- A single docker-compose.yml file per host would control everything that needs to run locally.

**Comment by kormat** [comment]
Dockerising done by https://github.com/scionproto/scion/pull/1614, licensing being tracked in https://github.com/scionproto/scion/issues/1627
